import { Habit,HabitLog,HabitStatus,UserSettings,CategoryStats,StatusStats } from '../types';
const scoreMap:Record<HabitStatus,number|null>={done:1,partial:.5,missed:0,rest:null,empty:null};
export const statusLabels:Record<HabitStatus,string>={empty:'Non saisi',done:'Accompli',partial:'Partiel',missed:'Manqué',rest:'Repos'};
export const statusCycle:HabitStatus[]=['empty','done','partial','missed','rest'];
export function getStatusScore(s:HabitStatus, countEmpty=false, past=false){if(s==='empty'&&countEmpty&&past)return 0; return scoreMap[s];}
export function logFor(logs:HabitLog[],habitId:string,date:string){return logs.find(l=>l.habitId===habitId&&l.date===date)?.status||'empty'}
export function setLog(logs:HabitLog[],habitId:string,date:string,status:HabitStatus){const i=logs.findIndex(l=>l.habitId===habitId&&l.date===date); if(i>=0){const n=[...logs]; n[i]={habitId,date,status}; return n} return [...logs,{habitId,date,status}]}
const isPast=(date:string)=>new Date(date+'T23:59:59')<new Date();
export function calculateDayScore(habits:Habit[],logs:HabitLog[],date:string,settings:UserSettings){let got=0,total=0; for(const h of habits.filter(h=>h.active)){const sc=getStatusScore(logFor(logs,h.id,date),settings.compterNonSaisisCommeManques,isPast(date)); if(sc!==null){got+=sc; total++}} return total?Math.round(got/total*100):0}
export function calculateSuccessRate(habits:Habit[],logs:HabitLog[],settings:UserSettings){let got=0,total=0; for(const l of logs){const sc=getStatusScore(l.status,settings.compterNonSaisisCommeManques,isPast(l.date)); if(sc!==null){got+=sc; total++}} return total?Math.round(got/total*100):0}
export function calculateMonthScore(h:Habit[],l:HabitLog[],year:number,month:number,s:UserSettings){const days=new Date(year,month+1,0).getDate(); let sum=0; for(let d=1;d<=days;d++)sum+=calculateDayScore(h,l,`${year}-${String(month+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,s); return Math.round(sum/days)}
export function calculateYearScore(h:Habit[],l:HabitLog[],year:number,s:UserSettings){return Math.round(Array.from({length:12},(_,m)=>calculateMonthScore(h,l,year,m,s)).reduce((a,b)=>a+b,0)/12)}
export function calculateCurrentStreak(h:Habit[],l:HabitLog[],s:UserSettings){let streak=0; const dt=new Date(); for(let i=0;i<365;i++){const date=dt.toISOString().slice(0,10); if(calculateDayScore(h,l,date,s)>=70)streak++; else break; dt.setDate(dt.getDate()-1)} return streak}
export function calculateBestStreak(h:Habit[],l:HabitLog[],s:UserSettings){let best=0,cur=0; const dt=new Date(s.anneeActive,0,1); for(let i=0;i<366;i++){const date=dt.toISOString().slice(0,10); cur=calculateDayScore(h,l,date,s)>=70?cur+1:0; best=Math.max(best,cur); dt.setDate(dt.getDate()+1)} return best}
export function calculateDisciplinedDays(h:Habit[],l:HabitLog[],year:number,s:UserSettings){let n=0; for(let m=0;m<12;m++)for(let d=1;d<=new Date(year,m+1,0).getDate();d++)if(calculateDayScore(h,l,`${year}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,s)>=70)n++; return n}
export function calculateHabitMonthlyRates(habits:Habit[],logs:HabitLog[],year:number,settings:UserSettings){return habits.slice(0,30).map(h=>({nom:h.nom,values:Array.from({length:12},(_,m)=>{const ls=logs.filter(l=>l.habitId===h.id&&l.date.startsWith(`${year}-${String(m+1).padStart(2,'0')}`)); let got=0,total=0; for(const x of ls){const sc=getStatusScore(x.status,settings.compterNonSaisisCommeManques,isPast(x.date)); if(sc!==null){got+=sc; total++}} return total?Math.round(got/total*100):-1})}))}
export function calculateCategoryStats(h:Habit[],l:HabitLog[],s:UserSettings):CategoryStats[]{const map=new Map<string,Habit[]>(); for(const habit of h){map.set(habit.categorie,[...(map.get(habit.categorie)||[]),habit])} return Array.from(map.values()).map(arr=>{const ids=arr.map(x=>x.id); const ls=l.filter(x=>ids.includes(x.habitId)); return {categorie:arr[0].categorie,score:calculateSuccessRate(arr,ls,s),total:ls.length}})}
export function calculateStatusStats(logs:HabitLog[]):StatusStats[]{return (['done','partial','missed','rest','empty'] as HabitStatus[]).map(status=>({status,label:statusLabels[status],value:logs.filter(l=>l.status===status).length}))}
export function calculateTopHabits(h:Habit[],l:HabitLog[],s:UserSettings){return h.map(x=>({nom:x.nom,score:calculateSuccessRate([x],l.filter(y=>y.habitId===x.id),s)})).sort((a,b)=>b.score-a.score).slice(0,10)}
export function calculateFragileHabits(h:Habit[],l:HabitLog[],s:UserSettings){return h.map(x=>({nom:x.nom,score:calculateSuccessRate([x],l.filter(y=>y.habitId===x.id),s)})).sort((a,b)=>a.score-b.score).slice(0,6)}
export function calculateAntiProcrastinationIndex(h:Habit[],l:HabitLog[],s:UserSettings){const ids=h.filter(x=>['Productivité','Anti-procrastination'].includes(x.categorie)||/prioritaire|Deep work|scrolling|pénible/i.test(x.nom)).map(x=>x.id); const score=calculateSuccessRate(h.filter(x=>ids.includes(x.id)),l.filter(x=>ids.includes(x.habitId)),s); const missed=l.filter(x=>ids.includes(x.habitId)&&x.status==='missed').length; return Math.max(0,Math.min(100,score-Math.min(15,Math.round(missed/10))))}
