import { AppTheme } from "../../../themes/theme-types";
export type SignatureWidgetProps = { theme: AppTheme; score: number; streak: number; activeHabits: number; year?: number; doneLogs?: number; disciplinedDays?: number };
export function SystemStatusWidget({score,streak}:SignatureWidgetProps){return <div className="theme-signature-widget system-status-widget" aria-label="Widget statut système"><span className="system-status-led"/> <b>SYSTÈME EN LIGNE</b><span className="system-status-metric">SYNC {score}%</span><span className="system-status-metric">SÉRIE {streak} J</span><div className="system-status-lines"><i/> <i/> <i/></div><svg viewBox="0 0 100 24" aria-hidden="true" focusable="false"><polyline points="0,18 20,14 35,20 55,5 75,12 100,3" fill="none" stroke="currentColor"/></svg></div>}
export function MoodBubbleWidget({score}:SignatureWidgetProps){return <div className="theme-signature-widget mood-bubble-widget" aria-label="Widget bulle d’humeur"><span className="mood-face">☺</span><strong className="mood-score">{score}%</strong><span>Belle progression</span><i className="mood-confetti"/><i className="mood-confetti"/><i className="mood-confetti"/></div>}
export function MemphisShapeScore({score,streak}:SignatureWidgetProps){return <div className="theme-signature-widget memphis-shape-score" aria-label="Widget score Memphis"><i className="memphis-circle"/><i className="memphis-triangle"/><i className="memphis-square"/><strong>{score}%</strong><span>RYTHME</span><small>{streak} j</small></div>}
export function AuroraFocusWidget({score,streak}:SignatureWidgetProps){return <div className="theme-signature-widget aurora-focus-widget" aria-label="Widget focus aurora"><i className="aurora-focus-halo"/><div className="aurora-focus-ring"><strong>{score}%</strong><span>FOCUS</span></div><small>{streak} j</small></div>}
export function GrowthBloomWidget({score,streak}:SignatureWidgetProps){return <div className="theme-signature-widget growth-bloom-widget" aria-label="Widget floraison"><svg className="growth-flower" viewBox="0 0 64 64" aria-hidden="true" focusable="false"><g fill="currentColor"><circle cx="32" cy="13" r="10"/><circle cx="50" cy="28" r="10"/><circle cx="43" cy="50" r="10"/><circle cx="21" cy="50" r="10"/><circle cx="14" cy="28" r="10"/></g><circle cx="32" cy="32" r="9" fill="#ffd166"/></svg><strong className="growth-score">{score}%</strong><span>ÇA POUSSE</span><small>{streak} j</small><svg className="growth-leaf" viewBox="0 0 40 24" aria-hidden="true" focusable="false"><path d="M2 22C8 3 27 0 38 4 29 23 13 25 2 22Z" fill="currentColor"/></svg></div>}
export function ArcadePlayerHud({score,streak,activeHabits,doneLogs}:SignatureWidgetProps){const level=Math.max(1,Math.floor(score/10)+1), xp=score*37, coins=doneLogs ?? activeHabits*25;return <div className="theme-signature-widget arcade-player-hud" aria-label="Widget HUD joueur"><span className="pixel-sprite"/><div className="arcade-player-line"><b>JOUEUR 1</b><span className="arcade-level">NIV {level}</span><span className="arcade-xp">XP {xp}</span><span className="arcade-coins">◉ {coins}</span></div><div className="arcade-xp-bar">{Array.from({length:10},(_,i)=><i className="arcade-xp-segment" data-on={i<Math.round(score/10)} key={i}/>)}</div><small>SÉRIE {streak} J</small></div>}
export function CosmicOrbitScore({score,streak}:SignatureWidgetProps){return <div className="theme-signature-widget cosmic-orbit-score" aria-label="Widget score orbital"><i className="cosmic-ring"/><i className="cosmic-planet"/><i className="cosmic-star"/><i className="cosmic-star"/><i className="cosmic-star"/><strong className="cosmic-score">{score}%</strong><small>{streak} j</small></div>}
export function KawaiiRewardCollection({score,streak,disciplinedDays}:SignatureWidgetProps){return <div className="theme-signature-widget kawaii-reward-widget" aria-label="Widget collection kawaii"><svg className="kawaii-mascot" viewBox="0 0 80 90" aria-hidden="true" focusable="false"><ellipse cx="28" cy="18" rx="10" ry="22" fill="#fff"/><ellipse cx="52" cy="18" rx="10" ry="22" fill="#fff"/><circle cx="40" cy="50" r="28" fill="#fff"/><circle cx="30" cy="48" r="3"/><circle cx="50" cy="48" r="3"/><path d="M31 60q9 8 18 0" fill="none" stroke="#222" strokeWidth="3"/><circle cx="22" cy="56" r="5" fill="#ff9ecb"/><circle cx="58" cy="56" r="5" fill="#ff9ecb"/></svg><span className="kawaii-stars">★ {disciplinedDays??score}</span><span className="kawaii-hearts">♥ {streak}</span><b className="kawaii-badge">Récompense</b><span className="kawaii-happiness">Bonheur {score}%</span><i className="kawaii-reward-bar"/></div>}
export function BrutalistManifesto({score,streak}:SignatureWidgetProps){return <div className="theme-signature-widget brutalist-manifesto" aria-label="Widget manifeste brutaliste"><b className="brutalist-word">PAS D’EXCUSE</b><strong>{score}%</strong><span>{streak} J</span><i className="brutalist-color-block"/><i className="brutalist-color-block"/><i className="brutalist-color-block"/><em className="brutalist-vertical">PROGRÈS</em></div>}
export function EditorialQuoteWidget({score,streak,year}:SignatureWidgetProps){return <div className="theme-signature-widget editorial-quote-widget" aria-label="Widget citation éditoriale"><span className="editorial-edition">ÉDITION {year}</span><strong className="editorial-score">{score}%</strong><small>{streak} j</small><b>CURATE YOUR LIFE</b><i className="editorial-line"/></div>}
export function ComicHeroMission({score,streak}:SignatureWidgetProps){return <div className="theme-signature-widget comic-hero-mission" aria-label="Widget mission héroïque"><span className="comic-speech">MISSION DU JOUR</span><i className="comic-burst"/><i className="comic-lightning">⚡</i><strong className="comic-hero-score">{score}</strong><small>{streak} j</small><b>TU PEUX LE FAIRE</b></div>}
export function LiquidFlowScore({score,streak}:SignatureWidgetProps){return <div className="theme-signature-widget liquid-flow-score" aria-label="Widget flux actif"><i className="liquid-blob"/><i className="liquid-blob"/><div className="liquid-ring"><strong>{score}%</strong></div><span className="liquid-flow-label">FLUX ACTIF</span><small>{streak} j</small></div>}
